### ISSUE TITLE
Fuse error when trying to mount

### ISSUE THREAD

**Issue by quashtaki** [x1ppy/freezetag#3]
When running `freezetag mount -v music/Library/Ichiko\ Aoba/ /musiclibrary/' (doing a single artist as a test, but this happens with the main library too), I get the following error:

```
using existing database /home/nobody/.cache/freezetag/freezefs.db
scanning music/Library/Ichiko Aoba/ for files and freezetags...
adding cached file: music/Library/Ichiko Aoba/2018 - qp/01 夜明けのジュリアの谷の噴水.flac
adding cached file: music/Library/Ichiko Aoba/2018 - qp/02 テリフリアメ.flac
adding cached file: music/Library/Ichiko Aoba/2018 - qp/03 月の丘.flac
adding cached file: music/Library/Ichiko Aoba/2018 - qp/04 みなしごの雨.flac
adding cached file: music/Library/Ichiko Aoba/2018 - qp/05 誰かの世界.flac
adding cached file: music/Library/Ichiko Aoba/2018 - qp/06 卯月の朧唄.flac
adding cached file: music/Library/Ichiko Aoba/2018 - qp/07 水辺の妖精.flac
adding cached file: music/Library/Ichiko Aoba/2018 - qp/08 妖精の手招き.flac
adding cached file: music/Library/Ichiko Aoba/2018 - qp/09 羊のアンソニー.flac
adding cached file: music/Library/Ichiko Aoba/2018 - qp/10 海辺の葬列.flac
adding freezetag: music/Library/Ichiko Aoba/2018 - qp/Ff4972e18c3694abb-edfc26f2-da2d0da0.ftag
mounting /musiclibrary/
fuse: unknown option `volname=musiclibrary'
Traceback (most recent call last):
  File "/usr/sbin/freezetag", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/freezetag/__main__.py", line 127, in main
    getattr(commands, args.command)(**vars(args))
  File "/usr/lib/python3.10/site-packages/freezetag/commands.py", line 431, in mount
    FreezeFS(verbose).mount(directory, mount_point)
  File "/usr/lib/python3.10/site-packages/freezetag/freezefs.py", line 147, in mount
    FUSE(self, mount_point, nothreads=True, foreground=True, fsname='freezefs', volname=Path(mount_point).name)
  File "/usr/lib/python3.10/site-packages/fuse.py", line 711, in __init__
    raise RuntimeError(err)
RuntimeError: 1
```

Removing the volname argument from the call and adding `debug=True' gives the following and then just hangs:

```
using existing database /home/nobody/.cache/freezetag/freezefs.db
scanning music/Library/Ichiko Aoba/ for files and freezetags...
adding cached file: music/Library/Ichiko Aoba/2018 - qp/01 夜明けのジュリアの谷の噴水.flac
adding cached file: music/Library/Ichiko Aoba/2018 - qp/02 テリフリアメ.flac
adding cached file: music/Library/Ichiko Aoba/2018 - qp/03 月の丘.flac
adding cached file: music/Library/Ichiko Aoba/2018 - qp/04 みなしごの雨.flac
adding cached file: music/Library/Ichiko Aoba/2018 - qp/05 誰かの世界.flac
adding cached file: music/Library/Ichiko Aoba/2018 - qp/06 卯月の朧唄.flac
adding cached file: music/Library/Ichiko Aoba/2018 - qp/07 水辺の妖精.flac
adding cached file: music/Library/Ichiko Aoba/2018 - qp/08 妖精の手招き.flac
adding cached file: music/Library/Ichiko Aoba/2018 - qp/09 羊のアンソニー.flac
adding cached file: music/Library/Ichiko Aoba/2018 - qp/10 海辺の葬列.flac
adding freezetag: music/Library/Ichiko Aoba/2018 - qp/Ff4972e18c3694abb-edfc26f2-da2d0da0.ftag
mounting /musiclibrary/
FUSE library version: 2.9.9
nullpath_ok: 0
nopath: 0
utime_omit_ok: 0
unique: 2, opcode: INIT (26), nodeid: 0, insize: 56, pid: 0
INIT: 7.32
flags=0x03fffffb
max_readahead=0x00020000
   INIT: 7.19
   flags=0x00000011
   max_readahead=0x00020000
   max_write=0x00020000
   max_background=0
   congestion_threshold=0
   unique: 2, success, outsize: 40
```
Not sure what's wrong unforunately
This is inside an arch docker container on Unraid

**Comment by CoordSpace** [comment]
What was the resolution for this? I still have the same issue when attempting to use freezetag via a docker container. I created a [fork](https://github.com/CoordSpace/freezetag) that incorporates the fixes recommended in the original release thread, just to get things working in linux for Ext4 (removal of volname and st_birthtime) but I can't get any further than a program freeze after Fuse takes over during mounting.

Host OS: Ubuntu 22.04.1 LTS
Container OS: Ubuntu 22.04.1 LTS

Looking at [other](https://stackoverflow.com/questions/55495197/how-to-use-fuse-inside-docker-compose-container-in-google-vm) [attempts](https://stackoverflow.com/questions/24966347/is-s3fs-not-able-to-mount-inside-docker-container) to use Fuse filesystems within docker containers, the furthest I got was with this:
`docker run --rm -it --privileged --cap-add=ALL --device /dev/fuse -v /lib/modules:/lib/modules -v /mnt/storage/freezetag-source-/:/music-src -v /tmp/music-frozen:/music-frozen coordspace/freezetag`

Not the most secure, I know, but it was just to test if there was a missing privilege or capability required to get this working.

Here's the debug output I get, very similar. No matter how long I wait, nothing shows up in the destination (frozen) directory.
```
# freezetag mount -v /music-src /music-frozen
creating database at /root/.cache/freezetag/freezefs.db
scanning /music-src for files and freezetags...
[snip]
adding freezetag: /music-src/F904437b863dedf5d-29ae6ba0-791645b6.ftag
mounting /music-frozen
FUSE library version: 2.9.9
nullpath_ok: 0
nopath: 0
utime_omit_ok: 0
unique: 2, opcode: INIT (26), nodeid: 0, insize: 56, pid: 0
INIT: 7.34
flags=0x33fffffb
max_readahead=0x00020000
   INIT: 7.19
   flags=0x00000011
   max_readahead=0x00020000
   max_write=0x00020000
   max_background=0
   congestion_threshold=0
   unique: 2, success, outsize: 40
```

**Comment by quashtaki** [comment]
Unfortunately did not find a solution. I did however find that mounting does work outside of docker, but the program doesn't terminate (however I just realised I'm not sure it's even supposed to?).  Although the mounted files aren't even accessible inside the docker container, so this doesn't even help.

**Comment by CoordSpace** [comment]
Yeah, mounting doesn't terminate since it's "live" and will match any future changes of the source files/tags to the state of the frozen filesystem. 

I guess Fuse just doesn't want to play nice with Docker's magic.  

Thanks for the update and good luck with your setup!

**Comment by undaunt** [comment]
@CoordSpace @quashtaki I believe I have this fixed

https://github.com/undaunt/freezetag/pull/4
